---
# The main openstack site deployment playbook

- hosts: servers-openstack
  user: root
  roles:
   - { role: common, tags: [ "openstack-common" ] }

- hosts: openstack-controller
  user: root
  roles:
   - { role: controller, tags: [ "openstack-controller" ] }

#- hosts: openstack_compute
#  user: root
#  roles:
#   - compute
 
 
