# glance add name=f17-jeos is_public=true disk_format=qcow2 container_format=ovf copy_from=http://berrange.fedorapeople.org/images/2012-11-15/f17-x86_64-openstack-sda.qcow2
---
# Upload an image
- hosts: openstack-controller
  vars:
    - admin_tenant_user: admin
    - admin_pass: secret
    - admin_tenant: admin
    - image_name: j17-jeos
    - image_url: "http://berrange.fedorapeople.org/images/2012-11-15/f17-x86_64-openstack-sda.qcow2"
  tasks: 
    - name: upload the file to glance
      glance_image: login_username={{ admin_tenant_user }} login_password={{ admin_pass }} 
                    login_tenant_name={{ admin_tenant }} name={{ image_name }} container_format=ovf 
                    disk_format=qcow2 state=present copy_from={{ image_url }}
         
